name: Dev Pipeline Deploy

'on':
  push:
    branches:
      - dev

permissions:
  contents: read
  id-token: write

jobs:
  deploy-dev:
    uses: ./.github/workflows/deploy_pipeline.yml
    secrets:
      AWS_ASSUME_ROLE_ARN: ${{ secrets.AWS_ASSUME_ROLE_ARN }}
    with:
      environment: dev
      aws-assume-role-arn: ${{ secrets.AWS_ASSUME_ROLE_ARN }}
      aws-region: "us-east-1"
      aws-statefile-s3-bucket: "product-ai-leonardojdss"
      aws-lock-dynamodb-table: "project-ai-terraform-lock"