name: prod Pipeline Deploy

'on':
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  deploy-prod:
    uses: ./.github/workflows/deploy_pipeline.yml
    with:
      environment: prod
      aws-region: "us-east-1"
      aws-statefile-s3-bucket: "product-ai-leonardojdss"
    secrets:
      AWS_ASSUME_ROLE_ARN: ${{ secrets.AWS_ASSUME_ROLE_ARN }}     